### PR TITLE
add "That recruitment company" sponsor

### PR DESCRIPTION
**Pull request by justusromijn**
Added logo asset, added link / image in sponsors page. Nothing more :)

sponsors

### CODE REVIEW

**Comment by Randynamic** [comment]
Can we make the logo a little bit smaller?

**Comment by Randynamic** [comment]
Really like the PR’s btw with the screenies

**Comment by justusromijn** [comment]
Better?

logo-smaller

**Comment by Randynamic** [comment]
super thx!!

**Pull request merged**
